name: Resize Images

on:
  push:
    paths:
      - wedding-image/**  # Trigger the workflow when images in wedding-image folder are added or modified

jobs:
  resize:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Install ImageMagick
    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    # Step 3: Create resized images
    - name: Resize Images
      run: |
        mkdir -p main-images thumbnail-images
        for file in wedding-image/*.{jpg,jpeg,png,gif}; do
          [ -e "$file" ] || continue  # Skip if no files match
          base=$(basename "$file")
          convert "$file" -resize 360x540\> "main-images/$base"  # Resize to 360x540
          convert "$file" -resize 81x121\> "thumbnail-images/$base"  # Resize to 81x121
        done

    # Step 4: Commit and push the resized images
    - name: Commit and push resized images
      run: |
        git config user.name "xanka"
        git config user.email "mikenps01457@gmail.com"
        git add main-images thumbnail-images
        git commit -m "Add resized images for main and thumbnails"
        git push
