name: Resize Images

on:
  push:
    paths:
      - wedding-images/**  # Trigger the workflow when images in wedding-images folder are added or modified
    branches:
      - master
      - main
    workflow_dispatch:

jobs:
  resize:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Install ImageMagick
    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    # Step 3: Create resized images
    - name: Resize Images
      run: |
        mkdir -p main-images thumbnail-images
        shopt -s nocaseglob
        convert wedding-images/DSC_5893.JPG -resize 1600x main-images/DSC_5893.jpeg
        convert wedding-images/DSC_5651.JPG -resize 580x main-images/DSC_5651.jpeg
        convert wedding-images/DSC_6186.JPG -resize 580x main-images/DSC_6186.jpeg

        for file in wedding-images/*.jpg; do
          [ -e "$file" ] || continue  # Skip if no files match
          base=$(basename "$file")
          convert "$file" -resize 560x870\> "main-images/$base"  # Resize to 560x870
          convert "$file" -resize 81x121\> "thumbnail-images/$base"  # Resize to 81x121
        done

    # Step 4: Commit and push the resized images
    - name: Commit and push resized images
      run: |
        git config user.name "xanka"
        git config user.email "mikenps01457@gmail.com"
        git add main-images thumbnail-images
        git commit -m "Add resized images for main and thumbnails"
        git push
